# Site settings
title: Team Cal ALC
email: kirstie.whitaker@gmail.com
url: https://TeamCalALC.github.io
description: "UC Berkeley AIDS/Lifecycle team website."
keywords: "aidslifecycle, alc, uc berkeley, go bears, roll on, fundraising, fight aids, hiv advocacy"
skills: "Riding to end AIDS"
meta_author: Whitaker Kirstie

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Kirstie Whitaker and the UC Berkeley ALC Team
  location: Where are we
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%23aidslifecycle
  - title: facebook
    url: https://www.facebook.com/groups/145319672770871
  - title: instagram
    url: https://www.instagram.com/explore/tags/aidslifecycle/?hl=en
  - title: github
    url: https://github.com/TeamCalALC/TeamCalALC.github.io

# Postal address (add as many lines as necessary)
address:
  - line: UC Berkeley
  - line: (and everywhere their alumni live)

# Credits content
credits: 'This website is build on the Freelancer theme: a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
